### ISSUE TITLE
SoundCloud Issue

### ISSUE THREAD

**Issue by hacknug** [morganestes/widont-part-deux#1]
First things first, thank you for putting out such an amazing plugin, but:

It's seems to be some kind of incompatibility between the SoundCloud player and Widon't on my site. When I enable the plugin all SoundCloud embed players disappear. Have you experienced the same issue?

**Comment by morganestes** [comment]
Are you using a plugin for SoundClound, or are you adding in a player through oEmbed?

**Comment by hacknug** [comment]
I'm using an <iframe>. 
    —

**Comment by morganestes** [comment]
I found an issue where the plugin is adding `&nbsp;` inside tags, rather than inside the content in the elements themselves. When using an `iframe` (either directly, or through oEmbed), the presence of the extra code is breaking the insertion of the content.

I have written a fix and am testing it tonight. If all goes well, you should see an update in the next day or so in your WP Plugins Admin panel.
